services:
  server:
    container_name: "go-mud-server"
    build:
      dockerfile: ./provisioning/Dockerfile.dev
    image: localhost/go-mud-server:${TAG:-latest}
    working_dir: /src
    networks:
      - mud_network
    environment:
      SERVICE_NAME: go-mud-server
      PORT: 33333
      CONFIG_PATH: /src/myconfig.yaml
    ports:
      - 33333:33333
      - 80:80
    volumes:
      - .:/src
      - go-mod-cache:/root/go/pkg/mod

  busybox:
    container_name: "server-logs"
    image: busybox
    command:
      - "tail"
      - "-F"
      - "/src/log/logfile.log"
    volumes:
      - .:/src

  terminal:
    container_name: "mud-terminal"
    build:
      dockerfile: ./provisioning/terminal/Dockerfile
      args:
        - BIN=mud-terminal
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mud_network
    environment:
      PORT: 33333
      SERVICE_NAME: mud-terminal
      LINES: 50
      COLUMNS: 120

volumes:
  go-mod-cache:

networks:
  mud_network:
    name: mud_network
